/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE designationBaseService PLEASE EDIT ../designation.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { DESIGNATION } from '../../domain/smsystem_db/designation';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../DESIGNATION.service.ts
 */

/*
 * SCHEMA DB DESIGNATION
 *
	{
		Dateofjoining: {
			type: 'Date'
		},
		designation: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		teachers: {
			type: Schema.ObjectId,
			ref : "DESIGNATION"
		},
	}
 *
 */
@Injectable()
export class DESIGNATIONBaseService {

    contextUrl: string = environment.endpoint + '/designation';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * DESIGNATIONService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: DESIGNATION): Observable<DESIGNATION> {
        return this.http
            .post<DESIGNATION>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * DESIGNATIONService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * DESIGNATIONService.findByteachers
    *   @description CRUD ACTION findByteachers
    *   @param Objectid key Id of model to search for
    *
    */
    findByTeachers(id: string): Observable<DESIGNATION[]> {
        return this.http
            .get<DESIGNATION[]>(this.contextUrl + '/findByteachers/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * DESIGNATIONService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<DESIGNATION> {
        return this.http
            .get<DESIGNATION>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * DESIGNATIONService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<DESIGNATION[]> {
        return this.http
            .get<DESIGNATION[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * DESIGNATIONService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: DESIGNATION): Observable<DESIGNATION> {
        return this.http
            .post<DESIGNATION>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
