/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE studentsBaseService PLEASE EDIT ../students.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { STUDENTS } from '../../domain/smsystem_db/students';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../STUDENTS.service.ts
 */

/*
 * SCHEMA DB STUDENTS
 *
	{
		DOB: {
			type: 'Date',
			required : true
		},
		First_Name: {
			type: 'String',
			required : true
		},
		Last_Name: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		Subjects: [{
			type: Schema.ObjectId,
			ref : "STUDENTS"
		}],
	}
 *
 */
@Injectable()
export class STUDENTSBaseService {

    contextUrl: string = environment.endpoint + '/student';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * STUDENTSService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: STUDENTS): Observable<STUDENTS> {
        return this.http
            .post<STUDENTS>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * STUDENTSService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * STUDENTSService.findBySubjects
    *   @description CRUD ACTION findBySubjects
    *   @param Objectid key Id of model to search for
    *
    */
    findBySubjects(id: string): Observable<STUDENTS[]> {
        return this.http
            .get<STUDENTS[]>(this.contextUrl + '/findBySubjects/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * STUDENTSService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<STUDENTS> {
        return this.http
            .get<STUDENTS>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * STUDENTSService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<STUDENTS[]> {
        return this.http
            .get<STUDENTS[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * STUDENTSService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: STUDENTS): Observable<STUDENTS> {
        return this.http
            .post<STUDENTS>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
