/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE teachersBaseService PLEASE EDIT ../teachers.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { TEACHERS } from '../../domain/smsystem_db/teachers';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../TEACHERS.service.ts
 */

/*
 * SCHEMA DB TEACHERS
 *
	{
		First_Name: {
			type: 'String',
			required : true
		},
		Last_Name: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		teachers: {
			type: Schema.ObjectId,
			ref : "DESIGNATION"
		},
	}
 *
 */
@Injectable()
export class TEACHERSBaseService {

    contextUrl: string = environment.endpoint + '/teachers';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * TEACHERSService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: TEACHERS): Observable<TEACHERS> {
        return this.http
            .post<TEACHERS>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * TEACHERSService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * TEACHERSService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<TEACHERS> {
        return this.http
            .get<TEACHERS>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * TEACHERSService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<TEACHERS[]> {
        return this.http
            .get<TEACHERS[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * TEACHERSService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: TEACHERS): Observable<TEACHERS> {
        return this.http
            .post<TEACHERS>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
